import type {
  Transaction,
  AIAlert,
  User,
  AccessLog,
  DashboardStats,
  BiometricData,
  Notification,
  StudentProfile,
  StudentPayment,
} from "./types";


export const mockAIAlerts: AIAlert[] = [
  {
    id: "a1",
    userId: "u3",
    userName: "Emily Rodriguez",
    type: "transaction",
    severity: "high",
    description:
      "Unusual transaction pattern detected - Large grant disbursement outside normal hours",
    timestamp: "2025-01-16T16:45:00Z",
    anomalyScore: 87,
    details: {
      transactionFrequency: 3.5,
      unusualTime: true,
      locationAnomaly: false,
    },
    resolved: false,
  },
  {
    id: "a2",
    userId: "u4",
    userName: "James Wilson",
    type: "behavioral",
    severity: "medium",
    description: "Typing rhythm deviation detected - 45% slower than baseline",
    timestamp: "2025-01-16T09:15:00Z",
    anomalyScore: 62,
    details: {
      typingRhythm: 55,
      accessPattern: "unusual",
    },
    resolved: false,
  },
  {
    id: "a3",
    userId: "u2",
    userName: "Dr. Michael Chen",
    type: "access",
    severity: "low",
    description: "Access from new device detected",
    timestamp: "2025-01-15T22:30:00Z",
    anomalyScore: 34,
    details: {
      accessPattern: "new_device",
      unusualTime: true,
    },
    resolved: true,
  },
  {
    id: "a4",
    userId: "u1",
    userName: "Sarah Johnson",
    type: "login",
    severity: "medium",
    description: "Multiple failed login attempts detected",
    timestamp: "2025-01-16T07:20:00Z",
    anomalyScore: 58,
    details: {
      failedLogins: 4,
      locationAnomaly: true,
    },
    resolved: false,
  },
];

export const mockAccessLogs: AccessLog[] = [
  {
    id: "l1",
    userId: "u3",
    userName: "Emily Rodriguez",
    action: "GRANT_DISBURSEMENT",
    resource: "/payments/grants",
    timestamp: "2025-01-16T16:45:00Z",
    ipAddress: "192.168.1.45",
    success: true,
    riskScore: 87,
  },
  {
    id: "l2",
    userId: "u1",
    userName: "Sarah Johnson",
    action: "LOGIN_FAILED",
    resource: "/auth/login",
    timestamp: "2025-01-16T07:20:00Z",
    ipAddress: "10.0.0.123",
    success: false,
    riskScore: 58,
  },
  {
    id: "l3",
    userId: "u2",
    userName: "Dr. Michael Chen",
    action: "VIEW_BUDGET",
    resource: "/faculty/budget",
    timestamp: "2025-01-15T22:30:00Z",
    ipAddress: "172.16.0.89",
    success: true,
    riskScore: 34,
  },
  {
    id: "l4",
    userId: "u4",
    userName: "James Wilson",
    action: "PAYMENT_SUBMIT",
    resource: "/payments/student-services",
    timestamp: "2025-01-16T09:15:00Z",
    ipAddress: "192.168.1.78",
    success: true,
    riskScore: 62,
  },
  {
    id: "l5",
    userId: "u5",
    userName: "Dr. Patricia Lee",
    action: "EXPENSE_REPORT",
    resource: "/departments/expenses",
    timestamp: "2025-01-13T11:00:00Z",
    ipAddress: "192.168.1.34",
    success: true,
    riskScore: 12,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalPayments: 94100,
  pendingTransactions: 17000,
  activeAlerts: 3,
  totalUsers: 1247,
  monthlyRevenue: 2847500,
  revenueChange: 12.5,
  transactionVolume: 342,
  volumeChange: -3.2,
};

export const mockBiometricData: BiometricData[] = [
  {
    userId: "u1",
    typingSpeed: 65,
    typingRhythm: 82,
    mouseMovementPattern: 78,
    accessTimePattern: ["08:00-10:00", "14:00-16:00", "19:00-21:00"],
    averageSessionDuration: 45,
    deviceFingerprint: "fp_student_001",
  },
  {
    userId: "u3",
    typingSpeed: 72,
    typingRhythm: 88,
    mouseMovementPattern: 85,
    accessTimePattern: ["09:00-12:00", "13:00-17:00"],
    averageSessionDuration: 120,
    deviceFingerprint: "fp_staff_003",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "security",
    title: "High-Risk Transaction Detected",
    message:
      "Emily Rodriguez initiated a large grant disbursement outside normal hours. Anomaly score: 87",
    timestamp: "2025-01-16T16:45:00Z",
    read: false,
    priority: "high",
    actionUrl: "/ai-insights",
    userId: "u3",
    userName: "Emily Rodriguez",
  },
  {
    id: "n2",
    type: "security",
    title: "Multiple Failed Login Attempts",
    message:
      "Sarah Johnson had 4 failed login attempts from an unusual location.",
    timestamp: "2025-01-16T07:20:00Z",
    read: false,
    priority: "medium",
    actionUrl: "/users/u1",
    userId: "u1",
    userName: "Sarah Johnson",
  },
  {
    id: "n3",
    type: "payment",
    title: "Payment Pending Approval",
    message:
      "James Wilson submitted a housing deposit payment of $2,500 awaiting approval.",
    timestamp: "2025-01-16T09:15:00Z",
    read: false,
    priority: "medium",
    actionUrl: "/students",
    userId: "u4",
    userName: "James Wilson",
  },
  {
    id: "n4",
    type: "security",
    title: "Behavioral Anomaly Detected",
    message:
      "Typing rhythm deviation detected for James Wilson - 45% slower than baseline.",
    timestamp: "2025-01-16T09:15:00Z",
    read: true,
    priority: "medium",
    actionUrl: "/ai-insights",
    userId: "u4",
    userName: "James Wilson",
  },
  {
    id: "n5",
    type: "payment",
    title: "Payment Completed",
    message:
      "Sarah Johnson's tuition payment of $15,000 has been successfully processed.",
    timestamp: "2025-01-15T10:30:00Z",
    read: true,
    priority: "low",
    actionUrl: "/students",
    userId: "u1",
    userName: "Sarah Johnson",
  },
  {
    id: "n6",
    type: "system",
    title: "System Maintenance Scheduled",
    message:
      "Scheduled maintenance on January 20, 2025 from 2:00 AM to 4:00 AM EST.",
    timestamp: "2025-01-15T08:00:00Z",
    read: true,
    priority: "low",
  },
  {
    id: "n7",
    type: "security",
    title: "New Device Access",
    message: "Dr. Michael Chen accessed the system from a new device.",
    timestamp: "2025-01-15T22:30:00Z",
    read: true,
    priority: "low",
    actionUrl: "/users/u2",
    userId: "u2",
    userName: "Dr. Michael Chen",
  },
  {
    id: "n8",
    type: "payment",
    title: "Faculty Budget Allocated",
    message:
      "Dr. Michael Chen's research equipment budget of $8,500 has been allocated.",
    timestamp: "2025-01-14T14:20:00Z",
    read: true,
    priority: "low",
    actionUrl: "/faculty",
    userId: "u2",
    userName: "Dr. Michael Chen",
  },
  {
    id: "n9",
    type: "user",
    title: "New User Registration",
    message:
      "A new student account has been created for the Spring 2025 semester.",
    timestamp: "2025-01-14T11:00:00Z",
    read: true,
    priority: "low",
    actionUrl: "/users",
  },
  {
    id: "n10",
    type: "system",
    title: "Security Scan Completed",
    message:
      "Weekly security scan completed. No critical vulnerabilities detected.",
    timestamp: "2025-01-13T03:00:00Z",
    read: true,
    priority: "low",
  },
];

export const mockStudentProfiles: StudentProfile[] = [
  {
    id: "s1",
    regNumber: "CS/2024/001",
    name: "Sarah Johnson",
    email: "sarah.johnson@student.edu",
    department: "Computer Science",
    program: "B.Sc Computer Science",
    level: "200 Level",
    enrollmentDate: "2024-09-01",
    totalPaid: 15450,
    totalPending: 8500,
  },
  {
    id: "s2",
    regNumber: "BUS/2023/156",
    name: "James Wilson",
    email: "james.wilson@student.edu",
    department: "Business Administration",
    program: "B.Sc Business Administration",
    level: "300 Level",
    enrollmentDate: "2023-09-01",
    totalPaid: 42000,
    totalPending: 17000,
  },
];

export const mockStudentPayments: StudentPayment[] = [
  {
    id: "sp1",
    studentId: "s1",
    type: "tuition",
    amount: 15000,
    status: "paid",
    dueDate: "2025-01-10",
    paidDate: "2025-01-15",
    semester: "Spring",
    academicYear: "2024/2025",
    description: "Spring 2025 Tuition Fee",
    reference: "TUI-2025-001",
  },
  {
    id: "sp2",
    studentId: "s1",
    type: "library",
    amount: 450,
    status: "paid",
    dueDate: "2025-01-10",
    paidDate: "2025-01-12",
    semester: "Spring",
    academicYear: "2024/2025",
    description: "Library Fee - Spring 2025",
    reference: "LIB-2025-034",
  },
  {
    id: "sp3",
    studentId: "s1",
    type: "accommodation",
    amount: 5000,
    status: "pending",
    dueDate: "2025-02-01",
    semester: "Spring",
    academicYear: "2024/2025",
    description: "Hostel Accommodation - Spring 2025",
  },
  {
    id: "sp4",
    studentId: "s1",
    type: "exam",
    amount: 3500,
    status: "pending",
    dueDate: "2025-03-15",
    semester: "Spring",
    academicYear: "2024/2025",
    description: "Examination Fee - Spring 2025",
  },
];
